### ISSUE TITLE
Restructure this repo a little

### ISSUE THREAD

**Issue by thchang** [vtopt/qnstop#2]
Hi @bamos ,

Would it be possible to do a minor restructuring of this repo?  I've been helping Dr. Watson get this repo cleaned up, and trying to make these codes easily available.  One way to do this, is by getting them listed on the Fortran Language website:
    https://fortran-lang.org/packages/numerical

I have another software package coming out soon, and when I ask them to add that, I can ask them to add QNSTOP as well in the same pull-request.  Here's what I think you should do before I request something like that, although admittedly, I am just making this structure up as I go, so other suggestions are also welcome:

 * Create a ``src`` directory, and place all current contents of ``master`` in the ``src`` directory
 * Create a ``docs`` directory, and merge all contents of ``gh-pages`` branch into the master branch's ``docs`` directory
 * Go to settings -> pages and change the target branch for your github pages to point at the ``master`` branch and the ``docs`` directory (I can do this for you if it doesn't let you do it yourself)
 * Create a short ``README.md`` file in ``master`` root, explaining the contents of each directory (e.g., " ``src`` contains ACM TOMS code, and ``docs`` contains website docs.  See the ``README`` in ``src`` for further usage details. ")
 * Add a LICENSE file in the base directory -- you can choose whatever license you want since QNSTOP was published post-2011:  https://www.acm.org/publications/policies/software-copyright-notice -- I've been using MIT License for these, but I've asked Dr. Watson if he has a different preference many times and he doesn't care.  IMHO, a "free-use" license like MIT, BSD 3-clause, or Apache 2 is preferable
 * You can check out the main branch of vtopt/DelaunaySparse as an example for some of these things, but I'm actually still in the process of making some of these changes there myself

I know you have other things to do besides continuing to maintain this repo, but I think it's worth our while to make these repositories easily accessible for the Fortran community!

Thanks,
---Tyler

**Comment by bamos** [comment]
Yes, done! I don't have permissions to update the target branch for gh pages, can you do that one for me? Let me know if there's anything else
